theme: minima
title: Ermina&Fabrizio Baby list
description: A web-service/blog that contains options for a baby list 
             and allows users to remove the items that they bought for everyone to see
author: ErminaPap
